version: '3'
#------------------------------------------------------------------
#
#
#             maintains image builder and pusher
#
#
#------------------------------------------------------------------
services:
 buildbot:
  image: reg_adrese:ports/image
  environment:
    - GH_WEBHOOK_PORT=gh_ports
    - GITHUB_TOKEN=tokens1234567890
    - LOCALREGISTRY=reg_adrese:ports

    - SETTINGS_nosaukums_image=nosaukums
    

  volumes:
    - ./docker_volumes/tmp:/tmp
    - /var/run/docker.sock:/var/run/docker.sock

  ports:
    - "ports:ports"

